import { LearningItem } from '../../types/vocabulary';
import { generateLanguageLibrary } from '../generateAllLanguages';

export function generateJapaneseDataset(): LearningItem[] {
  const verbs = [
    { w: '食べる', p: 'taberu', m: 'to eat', spec: { type: 'japanese', data: { kanji: '食べる', hiragana: 'たべる', romaji: 'taberu', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '飲む', p: 'nomu', m: 'to drink', spec: { type: 'japanese', data: { kanji: '飲む', hiragana: 'のむ', romaji: 'nomu', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '見る', p: 'miru', m: 'to see / watch', spec: { type: 'japanese', data: { kanji: '見る', hiragana: 'みる', romaji: 'miru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '聞く', p: 'kiku', m: 'to listen / hear', spec: { type: 'japanese', data: { kanji: '聞く', hiragana: 'きく', romaji: 'kiku', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '話す', p: 'hanasu', m: 'to speak / talk', spec: { type: 'japanese', data: { kanji: '話す', hiragana: 'はなす', romaji: 'hanasu', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '読む', p: 'yomu', m: 'to read', spec: { type: 'japanese', data: { kanji: '読む', hiragana: 'よむ', romaji: 'yomu', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '書く', p: 'kaku', m: 'to write', spec: { type: 'japanese', data: { kanji: '書く', hiragana: 'かく', romaji: 'kaku', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '買う', p: 'kau', m: 'to buy', spec: { type: 'japanese', data: { kanji: '買う', hiragana: 'かう', romaji: 'kau', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '売る', p: 'uru', m: 'to sell', spec: { type: 'japanese', data: { kanji: '売る', hiragana: 'うる', romaji: 'uru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '行く', p: 'iku', m: 'to go', spec: { type: 'japanese', data: { kanji: '行く', hiragana: 'いく', romaji: 'iku', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '来る', p: 'kuru', m: 'to come', spec: { type: 'japanese', data: { kanji: '来る', hiragana: 'くる', romaji: 'kuru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '帰る', p: 'kaeru', m: 'to return / go home', spec: { type: 'japanese', data: { kanji: '帰る', hiragana: 'かえる', romaji: 'kaeru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '歩く', p: 'aruku', m: 'to walk', spec: { type: 'japanese', data: { kanji: '歩く', hiragana: 'あるく', romaji: 'aruku', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '走る', p: 'hashiru', m: 'to run', spec: { type: 'japanese', data: { kanji: '走る', hiragana: 'はしる', romaji: 'hashiru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '乗る', p: 'noru', m: 'to ride / board', spec: { type: 'japanese', data: { kanji: '乗る', hiragana: 'のる', romaji: 'noru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '降りる', p: 'oriru', m: 'to get off / disembark', spec: { type: 'japanese', data: { kanji: '降りる', hiragana: 'おりる', romaji: 'oriru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '開ける', p: 'akeru', m: 'to open', spec: { type: 'japanese', data: { kanji: '開ける', hiragana: 'あける', romaji: 'akeru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '閉める', p: 'shimeru', m: 'to close', spec: { type: 'japanese', data: { kanji: '閉める', hiragana: 'しめる', romaji: 'shimeru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '待つ', p: 'matsu', m: 'to wait', spec: { type: 'japanese', data: { kanji: '待つ', hiragana: 'まつ', romaji: 'matsu', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '探す', p: 'sagasu', m: 'to search / look for', spec: { type: 'japanese', data: { kanji: '探す', hiragana: 'さがす', romaji: 'sagasu', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '洗う', p: 'arau', m: 'to wash', spec: { type: 'japanese', data: { kanji: '洗う', hiragana: 'あらう', romaji: 'arau', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '作る', p: 'tsukuru', m: 'to make / produce', spec: { type: 'japanese', data: { kanji: '作る', hiragana: 'つくる', romaji: 'tsukuru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '使う', p: 'tsukau', m: 'to use', spec: { type: 'japanese', data: { kanji: '使う', hiragana: 'つかう', romaji: 'tsukau', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '教える', p: 'oshieru', m: 'to teach / inform', spec: { type: 'japanese', data: { kanji: '教える', hiragana: 'おしえる', romaji: 'oshieru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '習う', p: 'narau', m: 'to learn', spec: { type: 'japanese', data: { kanji: '習う', hiragana: 'ならう', romaji: 'narau', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '始める', p: 'hajimeru', m: 'to begin / start', spec: { type: 'japanese', data: { kanji: '始める', hiragana: 'はじめる', romaji: 'hajimeru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '終わる', p: 'owaru', m: 'to end / finish', spec: { type: 'japanese', data: { kanji: '終わる', hiragana: 'おわる', romaji: 'owaru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '働く', p: 'hataraku', m: 'to work', spec: { type: 'japanese', data: { kanji: '働く', hiragana: 'はたらく', romaji: 'hataraku', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '休む', p: 'yasumu', m: 'to rest / take a break', spec: { type: 'japanese', data: { kanji: '休む', hiragana: 'やすむ', romaji: 'yasumu', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '考える', p: 'kangaeru', m: 'to think / consider', spec: { type: 'japanese', data: { kanji: '考える', hiragana: 'かんがえる', romaji: 'kangaeru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '決める', p: 'kimeru', m: 'to decide', spec: { type: 'japanese', data: { kanji: '決める', hiragana: 'きめる', romaji: 'kimeru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '予約する', p: 'yoyaku suru', m: 'to make a reservation', spec: { type: 'japanese', data: { kanji: '予約する', hiragana: 'よやくする', romaji: 'yoyaku suru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '注文する', p: 'chūmon suru', m: 'to order (food/goods)', spec: { type: 'japanese', data: { kanji: '注文する', hiragana: 'ちゅうもんする', romaji: 'chūmon suru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '支払う', p: 'shiharau', m: 'to pay', spec: { type: 'japanese', data: { kanji: '支払う', hiragana: 'しはらう', romaji: 'shiharau', jlptLevel: 'N3', politenessLevel: 'plain' } } },
    { w: '連絡する', p: 'renraku suru', m: 'to contact / get in touch', spec: { type: 'japanese', data: { kanji: '連絡する', hiragana: 'れんらくする', romaji: 'renraku suru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '案内する', p: 'annai suru', m: 'to guide / show around', spec: { type: 'japanese', data: { kanji: '案内する', hiragana: 'あんないする', romaji: 'annai suru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '紹介する', p: 'shōkai suru', m: 'to introduce', spec: { type: 'japanese', data: { kanji: '紹介する', hiragana: 'しょうかいする', romaji: 'shōkai suru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '掃除する', p: 'sōji suru', m: 'to clean up', spec: { type: 'japanese', data: { kanji: '掃除する', hiragana: 'そうじする', romaji: 'sōji suru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '練習する', p: 'renshū suru', m: 'to practice', spec: { type: 'japanese', data: { kanji: '練習する', hiragana: 'れんしゅうする', romaji: 'renshū suru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '準備する', p: 'junbi suru', m: 'to prepare', spec: { type: 'japanese', data: { kanji: '準備する', hiragana: 'じゅんびする', romaji: 'junbi suru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '確認する', p: 'kakunin suru', m: 'to confirm / check', spec: { type: 'japanese', data: { kanji: '確認する', hiragana: 'かくにんする', romaji: 'kakunin suru', jlptLevel: 'N3', politenessLevel: 'plain' } } },
    { w: '散歩する', p: 'sanpo suru', m: 'to take a walk', spec: { type: 'japanese', data: { kanji: '散歩する', hiragana: 'さんぽする', romaji: 'sanpo suru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '相談する', p: 'sōdan suru', m: 'to consult / discuss', spec: { type: 'japanese', data: { kanji: '相談する', hiragana: 'そうだんする', romaji: 'sōdan suru', jlptLevel: 'N3', politenessLevel: 'plain' } } },
    { w: '説明する', p: 'setsumei suru', m: 'to explain', spec: { type: 'japanese', data: { kanji: '説明する', hiragana: 'せつめいする', romaji: 'setsumei suru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '経験する', p: 'keiken suru', m: 'to experience', spec: { type: 'japanese', data: { kanji: '経験する', hiragana: 'けいけんする', romaji: 'keiken suru', jlptLevel: 'N3', politenessLevel: 'plain' } } },
    { w: '覚える', p: 'oboeru', m: 'to remember / memorize', spec: { type: 'japanese', data: { kanji: '覚える', hiragana: 'おぼえる', romaji: 'oboeru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '忘れる', p: 'wasureru', m: 'to forget', spec: { type: 'japanese', data: { kanji: '忘れる', hiragana: 'わすれる', romaji: 'wasureru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '手伝う', p: 'tetsudau', m: 'to help / assist', spec: { type: 'japanese', data: { kanji: '手伝う', hiragana: 'てつだう', romaji: 'tetsudau', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '届ける', p: 'todokeru', m: 'to deliver', spec: { type: 'japanese', data: { kanji: '届ける', hiragana: 'とどける', romaji: 'todokeru', jlptLevel: 'N3', politenessLevel: 'plain' } } },
    { w: '受け取る', p: 'uketoru', m: 'to receive / accept', spec: { type: 'japanese', data: { kanji: '受け取る', hiragana: 'うけとる', romaji: 'uketoru', jlptLevel: 'N3', politenessLevel: 'plain' } } },
    { w: '泊まる', p: 'tomaru', m: 'to stay overnight', spec: { type: 'japanese', data: { kanji: '泊まる', hiragana: 'とまる', romaji: 'tomaru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '乗り換える', p: 'norikaeru', m: 'to transfer (trains)', spec: { type: 'japanese', data: { kanji: '乗り換える', hiragana: 'のりかえる', romaji: 'norikaeru', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '降りる', p: 'oriru', m: 'to step down', spec: { type: 'japanese', data: { kanji: '降りる', hiragana: 'おりる', romaji: 'oriru', jlptLevel: 'N5', politenessLevel: 'plain' } } },
    { w: '楽しむ', p: 'tanoshimu', m: 'to enjoy', spec: { type: 'japanese', data: { kanji: '楽しむ', hiragana: 'たのしむ', romaji: 'tanoshimu', jlptLevel: 'N4', politenessLevel: 'plain' } } },
    { w: '喜ぶ', p: 'yorokobu', m: 'to be glad / rejoice', spec: { type: 'japanese', data: { kanji: '喜ぶ', hiragana: 'よろこぶ', romaji: 'yorokobu', jlptLevel: 'N3', politenessLevel: 'plain' } } },
  ];

  const nouns = [
    { w: '朝ご飯', p: 'asagohan', m: 'breakfast', c: 'Food, Cooking & Dining' },
    { w: '昼ご飯', p: 'hirugohan', m: 'lunch', c: 'Food, Cooking & Dining' },
    { w: '晩ご飯', p: 'bangohan', m: 'dinner', c: 'Food, Cooking & Dining' },
    { w: 'ラーメン', p: 'rāmen', m: 'ramen noodles', c: 'Food, Cooking & Dining' },
    { w: '寿司', p: 'sushi', m: 'sushi', c: 'Food, Cooking & Dining' },
    { w: '天ぷら', p: 'tempura', m: 'tempura', c: 'Food, Cooking & Dining' },
    { w: 'お茶', p: 'ocha', m: 'Japanese green tea', c: 'Food, Cooking & Dining' },
    { w: 'コーヒー', p: 'kōhī', m: 'coffee', c: 'Food, Cooking & Dining' },
    { w: 'ミネラルウォーター', p: 'mineraru wōtā', m: 'mineral water', c: 'Food, Cooking & Dining' },
    { w: '新幹線', p: 'shinkansen', m: 'bullet train', c: 'Travel, Transport & Directions' },
    { w: '電車', p: 'densha', m: 'train', c: 'Travel, Transport & Directions' },
    { w: '地下鉄', p: 'chikatetsu', m: 'subway', c: 'Travel, Transport & Directions' },
    { w: 'タクシー', p: 'takushī', m: 'taxi', c: 'Travel, Transport & Directions' },
    { w: '空港', p: 'kūkō', m: 'airport', c: 'Travel, Transport & Directions' },
    { w: '東京駅', p: 'Tōkyō eki', m: 'Tokyo station', c: 'Travel, Transport & Directions' },
    { w: '温泉旅館', p: 'onsen ryokan', m: 'hot spring inn', c: 'Travel, Transport & Directions' },
    { w: '新幹線切符', p: 'shinkansen kippu', m: 'bullet train ticket', c: 'Travel, Transport & Directions' },
    { w: 'パスポート', p: 'pasupōto', m: 'passport', c: 'Travel, Transport & Directions' },
    { w: 'スーツケース', p: 'sūtsukēsu', m: 'suitcase', c: 'Travel, Transport & Directions' },
    { w: '観光名所', p: 'kankō meisho', m: 'tourist sightseeing spot', c: 'Travel, Transport & Directions' },
    { w: '案内所', p: 'annaijo', m: 'information desk', c: 'Travel, Transport & Directions' },
    { w: '財布', p: 'saifu', m: 'wallet', c: 'Shopping, Money & Finance' },
    { w: '現金', p: 'genkin', m: 'cash money', c: 'Shopping, Money & Finance' },
    { w: 'クレジットカード', p: 'kurejitto kādo', m: 'credit card', c: 'Shopping, Money & Finance' },
    { w: '領収書', p: 'ryōshūsho', m: 'receipt', c: 'Shopping, Money & Finance' },
    { w: 'スマートフォン', p: 'sumātofon', m: 'smartphone', c: 'Technology, Computers & Software' },
    { w: 'パソコン', p: 'pasokon', m: 'personal computer', c: 'Technology, Computers & Software' },
    { w: 'ワイヤレスイヤホン', p: 'waiyaresu iyahon', m: 'wireless earphones', c: 'Technology, Computers & Software' },
    { w: '充電器', p: 'jūdenki', m: 'battery charger', c: 'Technology, Computers & Software' },
    { w: '仕事のメール', p: 'shigoto no mēru', m: 'work email', c: 'Work, Office & Business' },
    { w: '契約書', p: 'keiyakusho', m: 'contract document', c: 'Work, Office & Business' },
    { w: '企画書', p: 'kikakusho', m: 'project proposal', c: 'Work, Office & Business' },
    { w: '会議室', p: 'kaigishitsu', m: 'meeting room', c: 'Work, Office & Business' },
    { w: '日本語の教科書', p: 'Nihongo no kyōkasho', m: 'Japanese textbook', c: 'School, Study & Education' },
    { w: '宿題', p: 'shukudai', m: 'homework', c: 'School, Study & Education' },
    { w: '試験の結果', p: 'shiken no kekka', m: 'exam results', c: 'School, Study & Education' },
    { w: '風邪薬', p: 'kazegusuri', m: 'cold medicine', c: 'Health, Body & Wellness' },
    { w: 'マスク', p: 'masuku', m: 'face mask', c: 'Health, Body & Wellness' },
    { w: '体温計', p: 'taionkei', m: 'thermometer', c: 'Health, Body & Wellness' },
    { w: '日本映画', p: 'Nihon eiga', m: 'Japanese film / movie', c: 'Entertainment, Music & Cinema' },
    { w: 'クラシック音楽', p: 'kurashikku ongaku', m: 'classical music', c: 'Entertainment, Music & Cinema' },
    { w: '折りたたみ傘', p: 'orit tatami gasa', m: 'folding umbrella', c: 'Daily Essentials' },
    { w: '家の鍵', p: 'ie no kagi', m: 'house key', c: 'Daily Essentials' },
    { w: 'お気に入りの靴', p: 'oki ni iri no kutsu', m: 'favorite shoes', c: 'Clothing & Fashion' },
    { w: '冬のコート', p: 'fuyu no kōto', m: 'winter coat', c: 'Clothing & Fashion' },
    { w: '記念写真', p: 'kinen shashin', m: 'commemorative photo', c: 'Hobbies & Leisure' },
    { w: '富士山の景色', p: 'Fujisan no keshiki', m: 'view of Mount Fuji', c: 'Nature, Geography & Cities' },
    { w: '春の桜', p: 'haru no sakura', m: 'spring cherry blossoms', c: 'Nature, Geography & Cities' },
    { w: '紅葉の季節', p: 'kōyō no kisetsu', m: 'autumn leaves season', c: 'Nature, Geography & Cities' },
    { w: '大切な思い出', p: 'taisetsu na omoide', m: 'precious memories', c: 'Feelings, Emotions & Moods' },
    { w: '将来の夢', p: 'shōrai no yume', m: 'future dream', c: 'Feelings, Emotions & Moods' },
    { w: '日本の文化', p: 'Nihon no bunka', m: 'Japanese culture', c: 'Culture, Holidays & Traditions' },
    { w: 'お正月', p: 'oshōgatsu', m: 'Japanese New Year', c: 'Culture, Holidays & Traditions' },
    { w: '着物', p: 'kimono', m: 'traditional kimono', c: 'Culture, Holidays & Traditions' },
    { w: '抹茶とお菓子', p: 'matcha to okashi', m: 'matcha and sweets', c: 'Food, Cooking & Dining' },
    { w: '温泉', p: 'onsen', m: 'hot spring', c: 'Travel, Transport & Directions' },
    { w: '神社と寺', p: 'jinja to tera', m: 'shrine and temple', c: 'Culture, Holidays & Traditions' },
    { w: 'お土産', p: 'omiyage', m: 'souvenir gift', c: 'Shopping, Money & Finance' },
    { w: 'コンビニ', p: 'konbini', m: 'convenience store', c: 'Shopping, Money & Finance' },
    { w: '図書館', p: 'toshokan', m: 'library', c: 'School, Study & Education' },
  ];

  const adjectives = [
    { w: '美味しい', p: 'oishii', m: 'delicious / tasty', c: 'Food, Cooking & Dining' },
    { w: '便利', p: 'benri', m: 'convenient', c: 'Daily Life & Routine' },
    { w: '静か', p: 'shizuka', m: 'quiet / peaceful', c: 'Daily Life & Routine' },
    { w: '綺麗', p: 'kirei', m: 'beautiful / clean', c: 'Daily Life & Routine' },
    { w: '親切', p: 'shinsetsu', m: 'kind / helpful', c: 'People, Family & Relationships' },
    { w: '優しい', p: 'yasashii', m: 'gentle / kind', c: 'People, Family & Relationships' },
    { w: '楽しい', p: 'tanoshii', m: 'fun / enjoyable', c: 'Hobbies, Arts & Pastimes' },
    { w: '嬉しい', p: 'ureshii', m: 'happy / delighted', c: 'Feelings, Emotions & Moods' },
    { w: '忙しい', p: 'isogashii', m: 'busy', c: 'Work, Office & Business' },
    { w: '元気', p: 'genki', m: 'healthy / lively', c: 'Health, Body & Wellness' },
  ];

  const phrases = [
    { w: 'おはようございます', p: 'ohayō gozaimasu', m: 'Good morning', c: 'Greetings & Introductions', exN: '皆さん、おはようございます！', exP: 'Mina-san, ohayō gozaimasu!', exT: 'Good morning everyone!' },
    { w: 'ありがとうございます', p: 'arigatō gozaimasu', m: 'Thank you very much', c: 'Politeness, Gratitude & Apologies', exN: 'ご親切にありがとうございます。', exP: 'Goshinsetsu ni arigatō gozaimasu.', exT: 'Thank you very much for your kindness.' },
    { w: 'すみません', p: 'sumimasen', m: 'Excuse me / Sorry', c: 'Politeness, Gratitude & Apologies', exN: 'すみません、メニューをお願いします。', exP: 'Sumimasen, menyū o onegai shimasu.', exT: 'Excuse me, please bring a menu.' },
    { w: 'お疲れ様でした', p: 'otsukaresama deshita', m: 'Thank you for your hard work', c: 'Work, Office & Business', exN: '今日の会議、お疲れ様でした！', exP: 'Kyō no kaigi, otsukaresama deshita!', exT: 'Thank you for your hard work in today’s meeting!' },
    { w: 'よろしくお願いします', p: 'yoroshiku onegai shimasu', m: 'Please treat me favorably', c: 'Greetings & Introductions', exN: 'これからどうぞよろしくお願いします。', exP: 'Kore kara dōzo yoroshiku onegai shimasu.', exT: 'I look forward to working with you.' },
  ];

  const questions = [
    { w: 'これは何ですか？', p: 'Kore wa nan desu ka?', m: 'What is this?', exN: 'すみません、これは何という料理ですか？', exP: 'Sumimasen, kore wa nan to iu ryōri desu ka?', exT: 'Excuse me, what kind of dish is this?' },
    { w: 'いくらですか？', p: 'Ikura desu ka?', m: 'How much is it?', exN: 'この絵葉書はいくらですか？', exP: 'Kono ehagaki wa ikura desu ka?', exT: 'How much is this postcard?' },
    { w: 'トイレはどこですか？', p: 'Toire wa doko desu ka?', m: 'Where is the restroom?', exN: 'あのう、トイレはどこにありますか？', exP: 'Anō, toire wa doko ni arimasu ka?', exT: 'Um, where is the restroom located?' },
    { w: '駅へはどう行きますか？', p: 'Eki e wa dō ikimasu ka?', m: 'How do I get to the station?', exN: 'ここから駅へはどう行きますか？', exP: 'Koko kara eki e wa dō ikimasu ka?', exT: 'How do I get to the station from here?' },
  ];

  const responses = [
    { w: 'はい、わかりました', p: 'Hai, wakarimashita', m: 'Yes, I understand', exN: 'はい、よくわかりました。', exP: 'Hai, yoku wakarimashita.', exT: 'Yes, I understood well.' },
    { w: '大丈夫です', p: 'Daijōbu desu', m: 'It is all right / No problem', exN: 'お気遣いなく、大丈夫です。', exP: 'Okidzukai naku, daijōbu desu.', exT: 'Do not worry about it, everything is fine.' },
    { w: '喜んで', p: 'Yorokonde', m: 'With pleasure / Gladly', exN: '喜んでお手伝いいたします。', exP: 'Yorokonde otetsudai itashimasu.', exT: 'I will gladly help you.' },
    { w: '失礼します', p: 'Shitsurei shimasu', m: 'Excuse me (entering/leaving)', exN: 'お先に失礼します。', exP: 'Osaki ni shitsurei shimasu.', exT: 'Excuse me for leaving ahead of you.' },
  ];

  return generateLanguageLibrary('ja', 'ja', {
    verbs,
    nouns,
    adjectives,
    phrases,
    questions,
    responses,
    buildExample: (v, n) => {
      return {
        n: `毎日の生活で${n.w}を${v.w}。`,
        p: `Mainichi no seikatsu de ${n.p} o ${v.p}.`,
        t: `In daily life, I ${v.m} ${n.m}.`,
      };
    },
  });
}
