import { LearningItem } from '../../types/vocabulary';
import { generateLanguageLibrary } from '../generateAllLanguages';

export function generateGermanDataset(): LearningItem[] {
  const verbs = [
    { w: 'essen', p: 'ˈɛsn̩', m: 'to eat', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'trinken', p: 'ˈtʁɪŋkn̩', m: 'to drink', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'sprechen', p: 'ˈʃpʁɛçn̩', m: 'to speak', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'hören', p: 'ˈhøːʁən', m: 'to hear / listen', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'sehen', p: 'ˈzeːən', m: 'to see', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'lesen', p: 'ˈleːzn̩', m: 'to read', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'schreiben', p: 'ˈʃʁaɪ̯bn̩', m: 'to write', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'kaufen', p: 'ˈkaʊ̯fn̩', m: 'to buy', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'verkaufen', p: 'fɛɐ̯ˈkaʊ̯fn̩', m: 'to sell', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'reisen', p: 'ˈʁaɪ̯zn̩', m: 'to travel', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'gehen', p: 'ˈɡeːən', m: 'to go / walk', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'laufen', p: 'ˈlaʊ̯fn̩', m: 'to run / walk', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'wohnen', p: 'ˈvoːnən', m: 'to live / reside', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'arbeiten', p: 'ˈaʁbaɪ̯tn̩', m: 'to work', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'sich ausruhen', p: 'zɪç ˈaʊ̯sˌʁuːən', m: 'to rest', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'denken', p: 'ˈdɛŋkn̩', m: 'to think', spec: { type: 'german', data: { verbType: 'irregular' } } },
    { w: 'entscheiden', p: 'ɛntˈʃaɪ̯dn̩', m: 'to decide', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'buchen', p: 'ˈbuːxn̩', m: 'to book / reserve', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'bestellen', p: 'bəˈʃtɛlən', m: 'to order', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'bezahlen', p: 'bəˈt͡saːlən', m: 'to pay', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'putzen', p: 'ˈpʊtsn̩', m: 'to clean', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'lernen', p: 'ˈlɛʁnən', m: 'to learn / study', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'studieren', p: 'ʃtuˈdiːʁən', m: 'to study at university', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'helfen', p: 'ˈhɛlfn̩', m: 'to help', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'suchen', p: 'ˈzuːxn̩', m: 'to look for', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'finden', p: 'ˈfɪndn̩', m: 'to find', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'brauchen', p: 'ˈbʁaʊ̯xn̩', m: 'to need', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'wollen', p: 'ˈvɔlən', m: 'to want', spec: { type: 'german', data: { verbType: 'irregular' } } },
    { w: 'können', p: 'ˈkœnən', m: 'to be able / can', spec: { type: 'german', data: { verbType: 'irregular' } } },
    { w: 'kennen', p: 'ˈkɛnən', m: 'to know / be familiar with', spec: { type: 'german', data: { verbType: 'irregular' } } },
    { w: 'anrufen', p: 'ˈanˌʁuːfn̩', m: 'to call (phone)', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'senden', p: 'ˈzɛndn̩', m: 'to send', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'erhalten', p: 'ɛɐ̯ˈhaltn̩', m: 'to receive', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'öffnen', p: 'ˈœfnən', m: 'to open', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'schließen', p: 'ˈʃliːsn̩', m: 'to close', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'nehmen', p: 'ˈneːmən', m: 'to take', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'warten', p: 'ˈvaʁtn̩', m: 'to wait', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'beginnen', p: 'bəˈɡɪnən', m: 'to begin', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'beenden', p: 'bəˈʔɛndn̩', m: 'to finish / end', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'kochen', p: 'ˈkɔxn̩', m: 'to cook', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'üben', p: 'ˈyːbn̩', m: 'to practice', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'organisieren', p: 'ɔʁɡaniˈziːʁən', m: 'to organize', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'teilen', p: 'ˈtaɪ̯lən', m: 'to share', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'besuchen', p: 'bəˈzuːxn̩', m: 'to visit', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'verstehen', p: 'fɛɐ̯ˈʃteːən', m: 'to understand', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'sich erinnern', p: 'zɪç ɛɐ̯ˈʔɪnɐn', m: 'to remember', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'vergessen', p: 'fɛɐ̯ˈɡɛsn̩', m: 'to forget', spec: { type: 'german', data: { verbType: 'strong' } } },
    { w: 'bevorzugen', p: 'bəˈfoːɐ̯ˌt͡suːɡn̩', m: 'to prefer', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'wechseln', p: 'ˈvɛksl̩n', m: 'to change / exchange', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'benutzen', p: 'bəˈnʊtsn̩', m: 'to use', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'mitbringen', p: 'ˈmɪtˌbʁɪŋən', m: 'to bring along', spec: { type: 'german', data: { verbType: 'irregular' } } },
    { w: 'zeigen', p: 'ˈt͡saɪ̯ɡn̩', m: 'to show', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'erklären', p: 'ɛɐ̯ˈklɛːʁən', m: 'to explain', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'vorstellen', p: 'ˈfoːɐ̯ˌʃtɛlən', m: 'to introduce / imagine', spec: { type: 'german', data: { verbType: 'weak' } } },
    { w: 'treffen', p: 'ˈtʁɛfn̩', m: 'to meet', spec: { type: 'german', data: { verbType: 'strong' } } },
  ];

  const nouns = [
    { w: 'das Frühstück', p: 'das ˈfʁyːˌʃtʏk', m: 'the breakfast', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'neuter', article: 'das', plural: 'die Frühstücke' } } },
    { w: 'das Mittagessen', p: 'das ˈmɪtaːkˌʔɛsn̩', m: 'the lunch', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'neuter', article: 'das', plural: 'die Mittagessen' } } },
    { w: 'das Abendessen', p: 'das ˈʔaːbn̩tˌʔɛsn̩', m: 'the dinner', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'neuter', article: 'das', plural: 'die Abendessen' } } },
    { w: 'das frische Brot', p: 'das ˈfʁɪʃə bʁoːt', m: 'the fresh bread', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'der warme Kaffee', p: 'deːɐ̯ ˈvaʁmə ˈkafe', m: 'the warm coffee', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'das Mineralwasser', p: 'das mineˈʁaːlˌvasɐ', m: 'the mineral water', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'das kühle Bier', p: 'das ˈkyːlə biːɐ̯', m: 'the cold beer', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'der deutsche Käse', p: 'deːɐ̯ ˈdɔɪ̯t͡ʃə ˈkɛːzə', m: 'the German cheese', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'der ICE-Zug', p: 'deːɐ̯ iː-tseː-ˈʔeː-tsuːk', m: 'the ICE high-speed train', c: 'Travel, Transport & Directions', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'die Fahrkarte', p: 'diː ˈfaːɐ̯ˌkaʁtə', m: 'the travel ticket', c: 'Travel, Transport & Directions', spec: { type: 'german', data: { gender: 'feminine', article: 'die', plural: 'die Fahrkarten' } } },
    { w: 'der Reisepass', p: 'deːɐ̯ ˈʁaɪ̯zəˌpas', m: 'the passport', c: 'Travel, Transport & Directions', spec: { type: 'german', data: { gender: 'masculine', article: 'der', plural: 'die Reisepässe' } } },
    { w: 'der Koffer', p: 'deːɐ̯ ˈkɔfɐ', m: 'the suitcase', c: 'Travel, Transport & Directions', spec: { type: 'german', data: { gender: 'masculine', article: 'der', plural: 'die Koffer' } } },
    { w: 'der Flughafen Frankfurt', p: 'deːɐ̯ ˈfluːkˌhaːfn̩', m: 'the Frankfurt airport', c: 'Travel, Transport & Directions', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'der Hauptbahnhof', p: 'deːɐ̯ ˈhaʊ̯ptbaːnˌhoːf', m: 'the central railway station', c: 'Travel, Transport & Directions', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'das gemütliche Hotel', p: 'das ɡəˈmyːtlɪçə hoˈtɛl', m: 'the cozy hotel', c: 'Travel, Transport & Directions', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'der Stadtplan', p: 'deːɐ̯ ˈʃtatˌplaːn', m: 'the city map', c: 'Travel, Transport & Directions', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'die Kreditkarte', p: 'diː kʁeˈdiːtˌkaʁtə', m: 'the credit card', c: 'Shopping, Money & Finance', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'das Bargeld', p: 'das ˈbaːɐ̯ˌɡɛlt', m: 'the cash money', c: 'Shopping, Money & Finance', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'die offizielle Rechnung', p: 'diː ˈʁɛçnʊŋ', m: 'the official invoice / receipt', c: 'Shopping, Money & Finance', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'das moderne Smartphone', p: 'das ˈsmaːɐ̯tˌfoːn', m: 'the modern smartphone', c: 'Technology, Computers & Software', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'der Laptop-Computer', p: 'deːɐ̯ ˈlɛpˌtɔp', m: 'the laptop computer', c: 'Technology, Computers & Software', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'die Kopfhörer', p: 'diː ˈkɔp͡fˌhøːʁɐ', m: 'the headphones', c: 'Technology, Computers & Software', spec: { type: 'german', data: { gender: 'masculine', article: 'die' } } },
    { w: 'die wichtige E-Mail', p: 'diː ˈiːmeːl', m: 'the important email', c: 'Work, Office & Business', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'der Arbeitsvertrag', p: 'deːɐ̯ ˈʔaʁbaɪ̯tsfɛɐ̯ˌtʁaːk', m: 'the employment contract', c: 'Work, Office & Business', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'das Team-Meeting', p: 'das ˈmiːtɪŋ', m: 'the team meeting', c: 'Work, Office & Business', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'das spannende Projekt', p: 'das pʁoˈjɛkt', m: 'the exciting project', c: 'Work, Office & Business', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'das Deutsch-Lehrbuch', p: 'das ˈleːɐ̯ˌbuːx', m: 'the German textbook', c: 'School, Study & Education', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'die Hausaufgaben', p: 'diː ˈhaʊ̯sʔaʊ̯fˌɡaːbn̩', m: 'the homework', c: 'School, Study & Education', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'die Abschlussprüfung', p: 'diː ˈpʁyːfʊŋ', m: 'the final examination', c: 'School, Study & Education', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'das wirksame Medikament', p: 'das medikaˈmɛnt', m: 'the effective medicine', c: 'Health, Body & Wellness', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'die Schutzmaske', p: 'diː ˈmaskə', m: 'the protective mask', c: 'Health, Body & Wellness', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'die warme Winterjacke', p: 'diː ˈjakə', m: 'the warm winter jacket', c: 'Clothing & Fashion', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'die bequemen Schuhe', p: 'diː ˈʃuːə', m: 'the comfortable shoes', c: 'Clothing & Fashion', spec: { type: 'german', data: { gender: 'masculine', article: 'die' } } },
    { w: 'die klassische Musik', p: 'diː muˈziːk', m: 'the classical music', c: 'Entertainment, Music & Cinema', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'der preisgekrönte Film', p: 'deːɐ̯ fɪlm', m: 'the award-winning film', c: 'Entertainment, Music & Cinema', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'der sonnige Strand', p: 'deːɐ̯ ʃtʁant', m: 'the sunny beach', c: 'Nature, Geography & Cities', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'die hohen Berge', p: 'diː ˈbɛʁɡə', m: 'the high mountains', c: 'Nature, Geography & Cities', spec: { type: 'german', data: { gender: 'masculine', article: 'die' } } },
    { w: 'der goldene Sonnenschein', p: 'deːɐ̯ ˈzɔnənˌʃaɪ̯n', m: 'the golden sunshine', c: 'Nature, Geography & Cities', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'der erfrischende Regen', p: 'deːɐ̯ ˈʁeːɡn̩', m: 'the refreshing rain', c: 'Nature, Geography & Cities', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'die reiche Kultur', p: 'diː kʊlˈtuːɐ̯', m: 'the rich culture', c: 'Culture, Holidays & Traditions', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'das traditionelle Fest', p: 'das fɛst', m: 'the traditional festival', c: 'Culture, Holidays & Traditions', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'das wunderbare Geschenk', p: 'das ɡəˈʃɛŋk', m: 'the wonderful gift', c: 'Shopping, Money & Finance', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'der Hausschlüssel', p: 'deːɐ̯ ˈʃlʏsl̩', m: 'the house key', c: 'Home, Living & Interior', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'das helle Zimmer', p: 'das ˈtsɪmɐ', m: 'the bright room', c: 'Home, Living & Interior', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'der leckere Nachtisch', p: 'deːɐ̯ ˈnaːxˌtɪʃ', m: 'the delicious dessert', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'das Glas Wasser', p: 'das ɡlaːs ˈvasɐ', m: 'the glass of water', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'der weiße Teller', p: 'deːɐ̯ ˈtɛlɐ', m: 'the white plate', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'die Restaurant-Rechnung', p: 'diː ˈʁɛçnʊŋ', m: 'the restaurant bill', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'der freundliche Kellner', p: 'deːɐ̯ ˈkɛlnɐ', m: 'the friendly waiter', c: 'Food, Cooking & Dining', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
    { w: 'das nette Gespräch', p: 'das ɡəˈʃpʁɛːç', m: 'the nice conversation', c: 'Communication', spec: { type: 'german', data: { gender: 'neuter', article: 'das' } } },
    { w: 'die echte Freundschaft', p: 'diː ˈfʁɔɪ̯ntʃaft', m: 'the true friendship', c: 'People, Family & Relationships', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'die liebevolle Familie', p: 'diː faˈmiːli̯ə', m: 'the loving family', c: 'People, Family & Relationships', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'die schöne Erinnerung', p: 'diː ɛɐ̯ˈʔɪnəʁʊŋ', m: 'the beautiful memory', c: 'Feelings, Emotions & Moods', spec: { type: 'german', data: { gender: 'feminine', article: 'die' } } },
    { w: 'der große Erfolg', p: 'deːɐ̯ ɛɐ̯ˈfɔlk', m: 'the great success', c: 'Feelings, Emotions & Moods', spec: { type: 'german', data: { gender: 'masculine', article: 'der' } } },
  ];

  const adjectives = [
    { w: 'lecker', p: 'ˈlɛkɐ', m: 'delicious / tasty', c: 'Food, Cooking & Dining' },
    { w: 'bequem', p: 'bəˈkveːm', m: 'comfortable', c: 'Daily Life & Routine' },
    { w: 'sauber', p: 'ˈzaʊ̯bɐ', m: 'clean', c: 'Home, Living & Interior' },
    { w: 'wunderschön', p: 'ˈvʊndɐˌʃøːn', m: 'wonderful / beautiful', c: 'Daily Life & Routine' },
    { w: 'freundlich', p: 'ˈfʁɔɪ̯ntlɪç', m: 'friendly / kind', c: 'People, Family & Relationships' },
    { w: 'interessant', p: 'ɪntəʁɛˈsant', m: 'interesting', c: 'School, Study & Education' },
    { w: 'einfach', p: 'ˈaɪ̯nfaχ', m: 'simple / easy', c: 'School, Study & Education' },
    { w: 'schwierig', p: 'ˈʃviːʁɪç', m: 'difficult', c: 'School, Study & Education' },
    { w: 'schnell', p: 'ʃnɛl', m: 'fast / quick', c: 'Travel, Transport & Directions' },
    { w: 'angenehm', p: 'ˈanɡəˌneːm', m: 'pleasant / agreeable', c: 'Daily Life & Routine' },
  ];

  const phrases = [
    { w: 'guten Morgen', p: 'ˈɡuːtn̩ ˈmɔʁɡn̩', m: 'Good morning', c: 'Greetings & Introductions', exN: 'Guten Morgen, wie geht es dir heute?', exP: 'ɡuːtn̩ mɔʁɡn̩, viː ɡeːt ɛs diːɐ̯ hɔɪ̯tə', exT: 'Good morning, how are you today?' },
    { w: 'vielen Dank', p: 'ˈfiːlən daŋk', m: 'Thank you very much', c: 'Politeness, Gratitude & Apologies', exN: 'Vielen Dank für deine großartige Unterstützung.', exP: 'fiːlən daŋk fyːɐ̯ daɪ̯nə ɡʁoːsʔaːɐ̯tɪɡə ʊntɐˈʃtʏtsʊŋ', exT: 'Thank you very much for your great support.' },
    { w: 'bitte schön', p: 'ˈbɪtə ʃøːn', m: 'You are very welcome', c: 'Politeness, Gratitude & Apologies', exN: 'Nichts zu danken, bitte schön!', exP: 'nɪçts tsuː daŋkn̩, bɪtə ʃøːn', exT: 'Nothing to thank for, you are very welcome!' },
    { w: 'auf Wiedersehen', p: 'aʊ̯f ˈviːdɐˌzeːən', m: 'Goodbye', c: 'Greetings & Introductions', exN: 'Einen schönen Tag noch und auf Wiedersehen!', exP: 'aɪ̯nən ʃøːnən taːk nɔx ʊnt aʊ̯f viːdɐzeːən', exT: 'Have a nice day and goodbye!' },
    { w: 'sehr gerne', p: 'zeːɐ̯ ˈɡɛʁnə', m: 'Very gladly', c: 'Everyday Responses & Reactions', exN: 'Sehr gerne, ich helfe dir dabei sofort.', exP: 'zeːɐ̯ ɡɛʁnə, ɪç hɛlfə diːɐ̯ daːbaɪ̯ zoˈfɔʁt', exT: 'Very gladly, I will help you with that right away.' },
  ];

  const questions = [
    { w: 'Wo ist die Toilette?', p: 'voː ɪst diː toˈlɛtə', m: 'Where is the restroom?', exN: 'Entschuldigung, wo ist die Toilette bitte?', exP: 'ɛntˈʃʊldɪɡʊŋ, voː ɪst diː tolɛtə bɪtə', exT: 'Excuse me, where is the restroom please?' },
    { w: 'Wie viel kostet das?', p: 'viː fiːl ˈkɔstət das', m: 'How much does that cost?', exN: 'Entschuldigen Sie, wie viel kostet dieses Buch?', exP: 'ɛntˈʃʊldɪɡn̩ ziː, viː fiːl kɔstət diːzəs buːx', exT: 'Excuse me, how much does this book cost?' },
    { w: 'Wie heißen Sie?', p: 'viː ˈhaɪ̯sn̩ ziː', m: 'What is your name?', exN: 'Freut mich, Sie kennenzulernen. Wie heißen Sie?', exP: 'fʁɔɪ̯t mɪç ziː kɛnəntsuːlɛʁnən. viː haɪ̯sn̩ ziː', exT: 'Pleased to meet you. What is your name?' },
    { w: 'Wie spät ist es?', p: 'viː ʃpɛːt ɪst ɛs', m: 'What time is it?', exN: 'Verzeihung, wissen Sie, wie spät es ist?', exP: 'fɛɐ̯ˈtsaɪ̯ʊŋ, vɪsn̩ ziː viː ʃpɛːt ɛs ɪst', exT: 'Pardon, do you know what time it is?' },
  ];

  const responses = [
    { w: 'natürlich gerne', p: 'naˈtyːɐ̯lɪç ˈɡɛʁnə', m: 'Naturally with pleasure', exN: 'Natürlich gerne, nimm dir ruhig Zeit.', exP: 'natyːɐ̯lɪç ɡɛʁnə, nɪm diːɐ̯ ʁuːɪç tsaɪ̯t', exT: 'Naturally with pleasure, take your time.' },
    { w: 'kein Problem', p: 'kaɪ̯n pʁoˈbleːm', m: 'No problem', exN: 'Mach dir keine Sorgen, das ist kein Problem.', exP: 'max diːɐ̯ kaɪ̯nə zɔʁɡn̩, das ɪst kaɪ̯n pʁobleːm', exT: 'Do not worry, that is no problem.' },
    { w: 'ich stimme zu', p: 'ɪç ˈʃtɪmə tsuː', m: 'I agree', exN: 'Genau so ist es, ich stimme vollkommen zu.', exP: 'ɡəˈnaʊ̯ zoː ɪst ɛs, ɪç ʃtɪmə fɔlˈkɔmən tsuː', exT: 'Exactly so, I completely agree.' },
    { w: 'guten Appetit', p: 'ˈɡuːtn̩ apəˈtiːt', m: 'Enjoy your meal', exN: 'Guten Appetit an alle am Tisch!', exP: 'ɡuːtn̩ apətiːt an alə am tɪʃ', exT: 'Enjoy your meal everyone at the table!' },
  ];

  return generateLanguageLibrary('de', 'de', {
    verbs,
    nouns,
    adjectives,
    phrases,
    questions,
    responses,
    buildExample: (v, n) => {
      return {
        n: `In meiner Freizeit möchte ich gerne ${n.w} ${v.w}.`,
        p: `ɪn maɪ̯nɐ ˈfʁaɪ̯ˌtsaɪ̯t ˈmœçtə ɪç ˈɡɛʁnə ${n.p} ${v.p}`,
        t: `In my free time, I would like to ${v.m} ${n.m}.`,
      };
    },
  });
}
