import { LearningItem } from '../../types/vocabulary';
import { generateLanguageLibrary } from '../generateAllLanguages';

export function generateSpanishDataset(): LearningItem[] {
  const verbs = [
    { w: 'comer', p: 'koˈmeɾ', m: 'to eat', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'beber', p: 'beˈbeɾ', m: 'to drink', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'hablar', p: 'aˈblaɾ', m: 'to speak / talk', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'escuchar', p: 'eskuˈt͡ʃaɾ', m: 'to listen', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'mirar', p: 'miˈɾaɾ', m: 'to look at / watch', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'leer', p: 'leˈeɾ', m: 'to read', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'escribir', p: 'eskɾiˈbiɾ', m: 'to write', spec: { type: 'spanish', data: { verbType: '-ir' } } },
    { w: 'comprar', p: 'komˈpɾaɾ', m: 'to buy / purchase', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'vender', p: 'benˈdeɾ', m: 'to sell', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'viajar', p: 'bjaˈxaɾ', m: 'to travel', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'caminar', p: 'kamiˈnaɾ', m: 'to walk', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'correr', p: 'koˈreɾ', m: 'to run', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'vivir', p: 'biˈbiɾ', m: 'to live / reside', spec: { type: 'spanish', data: { verbType: '-ir' } } },
    { w: 'trabajar', p: 'tɾabaˈxaɾ', m: 'to work', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'descansar', p: 'deskanˈsaɾ', m: 'to rest / relax', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'pensar', p: 'penˈsaɾ', m: 'to think', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'decidir', p: 'desiˈdiɾ', m: 'to decide', spec: { type: 'spanish', data: { verbType: '-ir' } } },
    { w: 'reservar', p: 'reseɾˈbaɾ', m: 'to book / reserve', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'pedir', p: 'peˈdiɾ', m: 'to ask for / order', spec: { type: 'spanish', data: { verbType: '-ir' } } },
    { w: 'pagar', p: 'paˈɣaɾ', m: 'to pay', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'limpiar', p: 'limˈpjaɾ', m: 'to clean', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'estudiar', p: 'estuˈdjaɾ', m: 'to study', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'aprender', p: 'apɾenˈdeɾ', m: 'to learn', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'ayudar', p: 'aʝuˈdaɾ', m: 'to help', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'buscar', p: 'busˈkaɾ', m: 'to search / look for', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'encontrar', p: 'enkonˈtɾaɾ', m: 'to find', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'necesitar', p: 'nesesiˈtaɾ', m: 'to need', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'querer', p: 'keˈɾeɾ', m: 'to want / love', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'conocer', p: 'konoˈseɾ', m: 'to know / meet (person/place)', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'llamar', p: 'ʝaˈmaɾ', m: 'to call', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'enviar', p: 'emˈbjaɾ', m: 'to send', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'recibir', p: 'resiˈbiɾ', m: 'to receive', spec: { type: 'spanish', data: { verbType: '-ir' } } },
    { w: 'abrir', p: 'aˈbɾiɾ', m: 'to open', spec: { type: 'spanish', data: { verbType: '-ir' } } },
    { w: 'cerrar', p: 'seˈraɾ', m: 'to close', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'tomar', p: 'toˈmaɾ', m: 'to take / drink', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'esperar', p: 'espeˈɾaɾ', m: 'to wait / hope', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'empezar', p: 'empeˈsaɾ', m: 'to begin / start', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'terminar', p: 'teɾmiˈnaɾ', m: 'to finish / end', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'cocinar', p: 'kosiˈnaɾ', m: 'to cook', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'practicar', p: 'pɾaktiˈkaɾ', m: 'to practice', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'organizar', p: 'oɾɣaniˈsaɾ', m: 'to organize', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'compartir', p: 'kompaɾˈtiɾ', m: 'to share', spec: { type: 'spanish', data: { verbType: '-ir' } } },
    { w: 'disfrutar', p: 'disfɾuˈtaɾ', m: 'to enjoy', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'celebrar', p: 'seleˈβɾaɾ', m: 'to celebrate', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'visitar', p: 'bisiˈtaɾ', m: 'to visit', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'entender', p: 'entenˈdeɾ', m: 'to understand', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'comprender', p: 'kompɾenˈdeɾ', m: 'to comprehend', spec: { type: 'spanish', data: { verbType: '-er' } } },
    { w: 'recordar', p: 'rekoɾˈdaɾ', m: 'to remember', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'olvidar', p: 'olbiˈdaɾ', m: 'to forget', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'preferir', p: 'pɾefeˈɾiɾ', m: 'to prefer', spec: { type: 'spanish', data: { verbType: '-ir' } } },
    { w: 'cambiar', p: 'kamˈbjaɾ', m: 'to change / exchange', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'usar', p: 'uˈsaɾ', m: 'to use', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'llevar', p: 'ʝeˈβaɾ', m: 'to carry / take along', spec: { type: 'spanish', data: { verbType: '-ar' } } },
    { w: 'traer', p: 'tɾaˈeɾ', m: 'to bring', spec: { type: 'spanish', data: { verbType: 'irregular' } } },
    { w: 'mostrar', p: 'mosˈtɾaɾ', m: 'to show / exhibit', spec: { type: 'spanish', data: { verbType: '-ar' } } },
  ];

  const nouns = [
    { w: 'el desayuno', p: 'el desaˈʝuno', m: 'the breakfast', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el', plural: 'los desayunos' } } },
    { w: 'el almuerzo', p: 'el alˈmweɾso', m: 'the lunch', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el', plural: 'los almuerzos' } } },
    { w: 'la cena', p: 'la ˈsena', m: 'the dinner', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la', plural: 'las cenas' } } },
    { w: 'la paella', p: 'la paˈeʝa', m: 'the paella', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la', plural: 'las paellas' } } },
    { w: 'el café', p: 'el kaˈfe', m: 'the coffee', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el', plural: 'los cafés' } } },
    { w: 'el agua', p: 'el ˈaɣwa', m: 'the water', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'feminine', article: 'el', plural: 'las aguas' } } },
    { w: 'el vino tinto', p: 'el ˈbino ˈtinto', m: 'the red wine', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el', plural: 'los vinos tintos' } } },
    { w: 'las tapas', p: 'las ˈtapas', m: 'the tapas appetizers', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'feminine', article: 'las', plural: 'las tapas' } } },
    { w: 'el tren de alta velocidad', p: 'el tɾen de ˈalta belosiˈdad', m: 'the high-speed train (AVE)', c: 'Travel, Transport & Directions', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el billete de viaje', p: 'el biˈʝete de ˈbjawe', m: 'the travel ticket', c: 'Travel, Transport & Directions', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el pasaporte', p: 'el pasaˈpoɾte', m: 'the passport', c: 'Travel, Transport & Directions', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la maleta grande', p: 'la maˈleta ˈɣɾande', m: 'the large suitcase', c: 'Travel, Transport & Directions', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el aeropuerto internacional', p: 'el aeɾoˈpweɾto', m: 'the international airport', c: 'Travel, Transport & Directions', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la estación central', p: 'la estaˈsjon senˈtɾal', m: 'the central station', c: 'Travel, Transport & Directions', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el hotel céntrico', p: 'el oˈtel ˈsentɾiko', m: 'the downtown hotel', c: 'Travel, Transport & Directions', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el mapa turístico', p: 'el ˈmapa tuˈɾistiko', m: 'the tourist map', c: 'Travel, Transport & Directions', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la tarjeta de crédito', p: 'la taɾˈxeta de ˈkɾedito', m: 'the credit card', c: 'Shopping, Money & Finance', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el dinero en efectivo', p: 'el diˈneɾo en efekˈtiβo', m: 'the cash money', c: 'Shopping, Money & Finance', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la factura oficial', p: 'la fakˈtuɾa ofiˈsjal', m: 'the official invoice', c: 'Shopping, Money & Finance', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el teléfono móvil', p: 'el teˈlefono ˈmoβil', m: 'the mobile phone', c: 'Technology, Computers & Software', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el ordenador portátil', p: 'el oɾdenaˈdoɾ poɾˈtatil', m: 'the laptop computer', c: 'Technology, Computers & Software', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'los auriculares inalámbricos', p: 'los awɾikuˈlaɾes', m: 'the wireless earphones', c: 'Technology, Computers & Software', spec: { type: 'spanish', data: { gender: 'masculine', article: 'los' } } },
    { w: 'el correo electrónico', p: 'el koˈre.o elekˈtɾoniko', m: 'the email message', c: 'Work, Office & Business', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el contrato de trabajo', p: 'el konˈtɾato de tɾaˈβaxo', m: 'the employment contract', c: 'Work, Office & Business', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la reunión importante', p: 'la rewˈnjon impoɾˈtante', m: 'the important meeting', c: 'Work, Office & Business', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el proyecto nuevo', p: 'el pɾoˈʝekto ˈnweβo', m: 'the new project', c: 'Work, Office & Business', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el libro de gramática', p: 'el ˈliβɾo de ɣɾaˈmatika', m: 'the grammar book', c: 'School, Study & Education', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'los deberes de clase', p: 'los deˈβeɾes de ˈklase', m: 'the class homework', c: 'School, Study & Education', spec: { type: 'spanish', data: { gender: 'masculine', article: 'los' } } },
    { w: 'el examen final', p: 'el ekˈsamen fiˈnal', m: 'the final exam', c: 'School, Study & Education', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la medicina para el resfriado', p: 'la mediˈsina', m: 'the cold medicine', c: 'Health, Body & Wellness', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la mascarilla sanitaria', p: 'la maskaˈɾiʝa', m: 'the health face mask', c: 'Health, Body & Wellness', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el termómetro digital', p: 'el teɾˈmometɾo', m: 'the digital thermometer', c: 'Health, Body & Wellness', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la ropa de invierno', p: 'la ˈropa de imˈbjeɾno', m: 'the winter clothing', c: 'Clothing & Fashion', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'los zapatos cómodos', p: 'los saˈpatos ˈkomodos', m: 'the comfortable shoes', c: 'Clothing & Fashion', spec: { type: 'spanish', data: { gender: 'masculine', article: 'los' } } },
    { w: 'la música clásica', p: 'la ˈmusika ˈklasika', m: 'the classical music', c: 'Entertainment, Music & Cinema', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la película española', p: 'la peˈlikula espaˈɲola', m: 'the Spanish film', c: 'Entertainment, Music & Cinema', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la hermosa playa', p: 'la eɾˈmosa ˈplaʝa', m: 'the beautiful beach', c: 'Nature, Geography & Cities', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la montaña nevada', p: 'la monˈtaɲa neˈβaða', m: 'the snowy mountain', c: 'Nature, Geography & Cities', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el sol brillante', p: 'el sol βɾiˈʝante', m: 'the shining sun', c: 'Nature, Geography & Cities', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la lluvia de primavera', p: 'la ˈʝuβja de pɾimaˈβeɾa', m: 'the spring rain', c: 'Nature, Geography & Cities', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la cultura hispana', p: 'la kulˈtuɾa isˈpana', m: 'the Hispanic culture', c: 'Culture, Holidays & Traditions', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la fiesta tradicional', p: 'la ˈfjesta tɾadysjoˈnal', m: 'the traditional celebration', c: 'Culture, Holidays & Traditions', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el regalo especial', p: 'el reˈɣalo espeˈsjal', m: 'the special gift', c: 'Shopping, Money & Finance', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la llave de la casa', p: 'la ˈʝaβe de la ˈkasa', m: 'the house key', c: 'Home, Living & Interior', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la habitación luminosa', p: 'la aβitaˈsjon lumiˈnosa', m: 'the luminous bedroom', c: 'Home, Living & Interior', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el sabroso café con leche', p: 'el saˈβɾoso kaˈfe', m: 'the tasty white coffee', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el plato principal', p: 'el ˈplato pɾinsiˈpal', m: 'the main course dish', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el postre casero', p: 'el ˈpostɾe kaˈseɾo', m: 'the homemade dessert', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el vaso de zumo fresco', p: 'el ˈbaso de ˈsumo', m: 'the glass of fresh juice', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la cuchara sopera', p: 'la kuˈt͡ʃaɾa soˈpeɾa', m: 'the soup spoon', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el tenedor limpio', p: 'el teneˈðoɾ ˈlimpjo', m: 'the clean fork', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el cuchillo afilado', p: 'el kuˈt͡ʃiʝo afiˈlaðo', m: 'the sharp knife', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la servilleta de papel', p: 'la seɾβiˈʝeta de paˈpel', m: 'the paper napkin', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la cuenta del restaurante', p: 'la ˈkwenta del restaβˈɾante', m: 'the restaurant bill', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el camarero amable', p: 'el kamaˈɾeɾo aˈmaβle', m: 'the friendly waiter', c: 'Food, Cooking & Dining', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'la buena conversación', p: 'la ˈbwena kombeɾsaˈsjon', m: 'the good conversation', c: 'Communication', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la sincera amistad', p: 'la sinˈseɾa amisˈtað', m: 'the sincere friendship', c: 'People, Family & Relationships', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la hermosa familia', p: 'la eɾˈmosa faˈmilja', m: 'the beautiful family', c: 'People, Family & Relationships', spec: { type: 'spanish', data: { gender: 'feminine', article: 'la' } } },
    { w: 'el recuerdo inolvidable', p: 'el reˈkweɾðo', m: 'the unforgettable memory', c: 'Feelings, Emotions & Moods', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
    { w: 'el gran éxito', p: 'el ɡɾan ˈeksito', m: 'the great success', c: 'Feelings, Emotions & Moods', spec: { type: 'spanish', data: { gender: 'masculine', article: 'el' } } },
  ];

  const adjectives = [
    { w: 'delicioso', p: 'deliˈsjoso', m: 'delicious', c: 'Food, Cooking & Dining' },
    { w: 'cómodo', p: 'ˈkomodo', m: 'comfortable', c: 'Daily Life & Routine' },
    { w: 'limpio', p: 'ˈlimpjo', m: 'clean', c: 'Home, Living & Interior' },
    { w: 'barato', p: 'baˈɾato', m: 'cheap / affordable', c: 'Shopping, Money & Finance' },
    { w: 'caro', p: 'ˈkaɾo', m: 'expensive', c: 'Shopping, Money & Finance' },
    { w: 'hermoso', p: 'eɾˈmoso', m: 'beautiful', c: 'Daily Life & Routine' },
    { w: 'amable', p: 'aˈmaβle', m: 'kind / friendly', c: 'People, Family & Relationships' },
    { w: 'interesante', p: 'inteɾeˈsante', m: 'interesting', c: 'School, Study & Education' },
    { w: 'fácil', p: 'ˈfasil', m: 'easy', c: 'School, Study & Education' },
    { w: 'difícil', p: 'diˈfisil', m: 'difficult', c: 'School, Study & Education' },
  ];

  const phrases = [
    { w: 'buenos días', p: 'ˈbwenos ˈdi.as', m: 'Good morning', c: 'Greetings & Introductions', exN: '¡Buenos días! ¿Cómo amaneciste hoy?', exP: 'Bwenos di.as, komo amanəsiste oi', exT: 'Good morning! How did you wake up today?' },
    { w: 'muchas gracias', p: 'ˈmut͡ʃas ˈɣɾasjas', m: 'Thank you very much', c: 'Politeness, Gratitude & Apologies', exN: 'Muchas gracias por toda tu valiosa ayuda.', exP: 'Mut͡ʃas ɣɾasjas poɾ toða tu baljosa aʝuða', exT: 'Thank you very much for all your valuable help.' },
    { w: 'de nada', p: 'de ˈnaða', m: 'You are welcome', c: 'Politeness, Gratitude & Apologies', exN: 'No hay de qué, de nada.', exP: 'No ai de ke, de naða', exT: 'Do not mention it, you are welcome.' },
    { w: 'hasta luego', p: 'ˈasta ˈlweɣo', m: 'See you later', c: 'Greetings & Introductions', exN: 'Nos vemos pronto, ¡hasta luego!', exP: 'Nos bemos pɾonto, asta lweɣo', exT: 'See you soon, until later!' },
    { w: 'con mucho gusto', p: 'kon ˈmut͡ʃo ˈɣusto', m: 'With great pleasure', c: 'Everyday Responses & Reactions', exN: 'Claro que sí, con mucho gusto te acompaño.', exP: 'Klaɾo ke si, kon mut͡ʃo ɣusto te akompaɲo', exT: 'Of course, with great pleasure I will accompany you.' },
  ];

  const questions = [
    { w: '¿Dónde está el baño?', p: 'ˈdonde esˈta el ˈbaɲo', m: 'Where is the restroom?', exN: 'Disculpe, ¿dónde está el baño por favor?', exP: 'Diskulpe, donde esta el baɲo poɾ faβoɾ', exT: 'Excuse me, where is the restroom please?' },
    { w: '¿Cuánto cuesta esto?', p: 'ˈkwanto ˈkwesta ˈesto', m: 'How much does this cost?', exN: 'Por favor, ¿cuánto cuesta este recuerdo?', exP: 'Poɾ faβoɾ, kwanto kwesta este rekweɾðo', exT: 'Please, how much does this souvenir cost?' },
    { w: '¿Cómo te llamas?', p: 'ˈkomo te ˈʝamas', m: 'What is your name?', exN: 'Hola, un placer conocerte, ¿cómo te llamas?', exP: 'Ola, un plaseɾ konoseɾte, komo te ʝamas', exT: 'Hello, pleasure to meet you, what is your name?' },
    { w: '¿Qué hora es?', p: 'ke ˈoɾa es', m: 'What time is it?', exN: 'Perdón, ¿me podrías decir qué hora es?', exP: 'Peɾðon, me poðɾi.as desiɾ ke oɾa es', exT: 'Pardon, could you tell me what time it is?' },
  ];

  const responses = [
    { w: 'claro que sí', p: 'ˈklaɾo ke ˈsi', m: 'Of course yes', exN: 'Claro que sí, cuenta conmigo.', exP: 'Klaɾo ke si, kwenta konmiɣo', exT: 'Of course, count on me.' },
    { w: 'no te preocupes', p: 'no te pɾe.oˈkupes', m: 'Do not worry', exN: 'Todo tiene solución, no te preocupes.', exP: 'Toðo tjene solusjon, no te pɾeokupes', exT: 'Everything has a solution, do not worry.' },
    { w: 'estoy de acuerdo', p: 'esˈtoi de aˈkweɾðo', m: 'I agree', exN: 'Totalmente, estoy de acuerdo con tu propuesta.', exP: 'Totalmente, estoi de akweɾðo kon tu pɾopwesta', exT: 'Totally, I agree with your proposal.' },
    { w: 'buen provecho', p: 'bwen pɾoˈβet͡ʃo', m: 'Enjoy your meal', exN: '¡Buen provecho a todos en la mesa!', exP: 'Bwen pɾoβet͡ʃo a toðos en la mesa', exT: 'Enjoy your meal everyone at the table!' },
  ];

  return generateLanguageLibrary('es', 'es', {
    verbs,
    nouns,
    adjectives,
    phrases,
    questions,
    responses,
    buildExample: (v, n) => {
      return {
        n: `Siempre me gusta ${v.w} ${n.w} cuando tengo tiempo.`,
        p: `Sjempre me ɣusta ${v.p} ${n.p}`,
        t: `I always like to ${v.m} ${n.m} when I have time.`,
      };
    },
  });
}
