import { LearningItem } from '../../types/vocabulary';
import { generateLanguageLibrary } from '../generateAllLanguages';

export function generateKoreanDataset(): LearningItem[] {
  const verbs = [
    { w: '먹다', p: 'meokda', m: 'to eat', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '마시다', p: 'masida', m: 'to drink', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '보다', p: 'boda', m: 'to see / look / watch', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '듣다', p: 'deutda', m: 'to listen / hear', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '말하다', p: 'malhada', m: 'to speak / talk', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '읽다', p: 'ikda', m: 'to read', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '쓰다', p: 'sseuda', m: 'to write / use', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '사다', p: 'sada', m: 'to buy', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '팔다', p: 'palda', m: 'to sell', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '가다', p: 'gada', m: 'to go', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '오다', p: 'oda', m: 'to come', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '돌아가다', p: 'doragada', m: 'to return / go back', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '걷다', p: 'geotda', m: 'to walk', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '달리다', p: 'dallida', m: 'to run', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '타다', p: 'tada', m: 'to ride / board', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '내리다', p: 'naerida', m: 'to get off / disembark', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '열다', p: 'yeolda', m: 'to open', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '닫다', p: 'datda', m: 'to close', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '기다리다', p: 'gidarida', m: 'to wait', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '찾다', p: 'chatda', m: 'to find / search for', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '씻다', p: 'ssitda', m: 'to wash', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '만들다', p: 'mandeulda', m: 'to make / create', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '가르치다', p: 'gareuchida', m: 'to teach', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '배우다', p: 'baeuda', m: 'to learn', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '시작하다', p: 'sijakhada', m: 'to start / begin', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '끝내다', p: 'kkeutnaeda', m: 'to finish / complete', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '일하다', p: 'ilhada', m: 'to work', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '쉬다', p: 'swida', m: 'to rest', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '생각하다', p: 'saenggakhada', m: 'to think', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '결정하다', p: 'gyeoljeonghada', m: 'to decide', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '예약하다', p: 'yeyakhada', m: 'to reserve / book', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '주문하다', p: 'jumunhada', m: 'to order', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '계산하다', p: 'gyesanhada', m: 'to pay / calculate', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '연락하다', p: 'yeollakhada', m: 'to contact', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '안내하다', p: 'annaehada', m: 'to guide / usher', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '소개하다', p: 'sogaehada', m: 'to introduce', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '청소하다', p: 'cheongsohada', m: 'to clean up', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '연습하다', p: 'yeonseuphada', m: 'to practice', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '준비하다', p: 'junbihada', m: 'to prepare', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '확인하다', p: 'hwaginhada', m: 'to confirm / check', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '산책하다', p: 'sanchaekhada', m: 'to take a stroll / walk', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '상의하다', p: 'sang-uihada', m: 'to consult / discuss', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '설명하다', p: 'seolmyeonghada', m: 'to explain', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '경험하다', p: 'gyeongheomhada', m: 'to experience', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '기억하다', p: 'gieokhada', m: 'to remember', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '잊어버리다', p: 'ijeobeorida', m: 'to forget completely', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '도와주다', p: 'dowajuda', m: 'to help out', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '보내다', p: 'bonaeda', m: 'to send / spend time', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '받다', p: 'batda', m: 'to receive', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '머무르다', p: 'meomureuda', m: 'to stay / remain', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '환승하다', p: 'hwanseunghada', m: 'to transfer (subway/bus)', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '즐기다', p: 'jeoulgida', m: 'to enjoy', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '기뻐하다', p: 'gippeohada', m: 'to rejoice / be glad', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '만나다', p: 'mannada', m: 'to meet', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
    { w: '선택하다', p: 'seontaekhada', m: 'to choose / select', spec: { type: 'korean', data: { speechLevel: 'informal-polite' } } },
  ];

  const nouns = [
    { w: '아침 식사', p: 'achim siksa', m: 'breakfast meal', c: 'Food, Cooking & Dining' },
    { w: '점심 식사', p: 'jeomsim siksa', m: 'lunch meal', c: 'Food, Cooking & Dining' },
    { w: '저녁 식사', p: 'jeonyeok siksa', m: 'dinner meal', c: 'Food, Cooking & Dining' },
    { w: '김치찌개', p: 'gimchijjigae', m: 'kimchi stew', c: 'Food, Cooking & Dining' },
    { w: '비빔밥', p: 'bibimbap', m: 'bibimbap mixed rice', c: 'Food, Cooking & Dining' },
    { w: '불고기', p: 'bulgogi', m: 'bulgogi marinated beef', c: 'Food, Cooking & Dining' },
    { w: '따뜻한 보리차', p: 'ttatteuthan boricha', m: 'warm barley tea', c: 'Food, Cooking & Dining' },
    { w: '아이스 아메리카노', p: 'aiseu amerikano', m: 'iced Americano coffee', c: 'Food, Cooking & Dining' },
    { w: '생수', p: 'saengsu', m: 'bottled mineral water', c: 'Food, Cooking & Dining' },
    { w: 'KTX 고속열차', p: 'KTX gosokyeolcha', m: 'KTX high-speed bullet train', c: 'Travel, Transport & Directions' },
    { w: '지하철 티머니 카드', p: 'jihacheol T-money kadeu', m: 'subway T-money card', c: 'Travel, Transport & Directions' },
    { w: '시내버스', p: 'sinaebeoseu', m: 'city bus', c: 'Travel, Transport & Directions' },
    { w: '택시', p: 'taeksi', m: 'taxi', c: 'Travel, Transport & Directions' },
    { w: '인천국제공항', p: 'Incheon gukjegonghang', m: 'Incheon International Airport', c: 'Travel, Transport & Directions' },
    { w: '서울역', p: 'Seoul-yeok', m: 'Seoul Station', c: 'Travel, Transport & Directions' },
    { w: '한옥 호텔', p: 'hanok hotel', m: 'traditional Hanok hotel', c: 'Travel, Transport & Directions' },
    { w: '비행기 표', p: 'bihaenggi pyo', m: 'airplane flight ticket', c: 'Travel, Transport & Directions' },
    { w: '여권', p: 'yeogwon', m: 'passport', c: 'Travel, Transport & Directions' },
    { w: '여행용 캐리어', p: 'yeohaengyong kaerieo', m: 'travel suitcase carrier', c: 'Travel, Transport & Directions' },
    { w: '관광 안내 지도', p: 'gwangwang annae jido', m: 'sightseeing guide map', c: 'Travel, Transport & Directions' },
    { w: '신용카드', p: 'sinyongkadeu', m: 'credit card', c: 'Shopping, Money & Finance' },
    { w: '현금', p: 'hyeongeum', m: 'cash money', c: 'Shopping, Money & Finance' },
    { w: '영수증', p: 'yeongsujeung', m: 'receipt', c: 'Shopping, Money & Finance' },
    { w: '최신 스마트폰', p: 'choesin seumateupon', m: 'latest smartphone', c: 'Technology, Computers & Software' },
    { w: '노트북 컴퓨터', p: 'noteubuk keompyuteo', m: 'laptop computer', c: 'Technology, Computers & Software' },
    { w: '무선 이어폰', p: 'museon ieopon', m: 'wireless earphones', c: 'Technology, Computers & Software' },
    { w: '보조배터리', p: 'bojobaeteori', m: 'power bank charger', c: 'Technology, Computers & Software' },
    { w: '업무 이메일', p: 'eommu imeil', m: 'business email', c: 'Work, Office & Business' },
    { w: '계약서', p: 'gyeyakseo', m: 'contract document', c: 'Work, Office & Business' },
    { w: '기획안', p: 'gihoegan', m: 'project plan proposal', c: 'Work, Office & Business' },
    { w: '회의실', p: 'hoe-uisil', m: 'conference room', c: 'Work, Office & Business' },
    { w: '한국어 교재', p: 'Hangugeo gyojae', m: 'Korean language textbook', c: 'School, Study & Education' },
    { w: '오늘의 숙제', p: 'oneul-ui sukje', m: 'today’s homework', c: 'School, Study & Education' },
    { w: '시험 성적', p: 'siheom seongjeok', m: 'examination grades', c: 'School, Study & Education' },
    { w: '감기약', p: 'gamgiyak', m: 'cold medicine', c: 'Health, Body & Wellness' },
    { w: '보건용 마스크', p: 'bogeonyong maseukeu', m: 'health face mask', c: 'Health, Body & Wellness' },
    { w: '따뜻한 패딩 코트', p: 'ttatteuthan paeding koteu', m: 'warm padded winter coat', c: 'Clothing & Fashion' },
    { w: '편안한 운동화', p: 'pyeon-anhan undonghwa', m: 'comfortable sneakers', c: 'Clothing & Fashion' },
    { w: 'K-POP 음악', p: 'K-POP eum-ak', m: 'K-pop music', c: 'Entertainment, Music & Cinema' },
    { w: '한국 드라마와 영화', p: 'Hanguk drama-wa yeonghwa', m: 'Korean drama and movie', c: 'Entertainment, Music & Cinema' },
    { w: '푸른 동해 바다', p: 'pureun Donghae bada', m: 'blue East Sea ocean', c: 'Nature, Geography & Cities' },
    { w: '설악산 풍경', p: 'Seoraksan punggyeong', m: 'Seoraksan mountain landscape', c: 'Nature, Geography & Cities' },
    { w: '밝은 햇살', p: 'balgeun haessal', m: 'bright sunshine', c: 'Nature, Geography & Cities' },
    { w: '봄날의 벚꽃', p: 'bomnal-ui beotkkot', m: 'spring cherry blossoms', c: 'Nature, Geography & Cities' },
    { w: '한국의 전통 문화', p: 'Hanguk-ui jeontong munhwa', m: 'Korean traditional culture', c: 'Culture, Holidays & Traditions' },
    { w: '추석 명절', p: 'Chuseok myeongjeol', m: 'Chuseok harvest holiday', c: 'Culture, Holidays & Traditions' },
    { w: '예쁜 한복', p: 'yeppeun hanbok', m: 'pretty Hanbok traditional attire', c: 'Culture, Holidays & Traditions' },
    { w: '정성스런 선물', p: 'jeongseongseureon seonmul', m: 'heartfelt gift', c: 'Shopping, Money & Finance' },
    { w: '집 열쇠', p: 'jip yeolsoe', m: 'house key', c: 'Home, Living & Interior' },
    { w: '아늑한 방', p: 'aneukhan bang', m: 'cozy room', c: 'Home, Living & Interior' },
    { w: '달콤한 디저트', p: 'dalkomhan dijeoteu', m: 'sweet dessert', c: 'Food, Cooking & Dining' },
    { w: '시원한 물 한 잔', p: 'siwonhan mul han jan', m: 'a glass of refreshing water', c: 'Food, Cooking & Dining' },
    { w: '깔끔한 접시', p: 'kkalkkeumhan jeopsi', m: 'neat plate dish', c: 'Food, Cooking & Dining' },
    { w: '식당 계산서', p: 'sikdang gyesanseo', m: 'restaurant bill', c: 'Food, Cooking & Dining' },
    { w: '친절한 직원', p: 'chinjeolhan jigwon', m: 'kind staff member', c: 'Food, Cooking & Dining' },
    { w: '즐거운 대화', p: 'jeulgeoun daehwa', m: 'pleasant conversation', c: 'Communication' },
    { w: '진실한 우정', p: 'jinsilhan ujeong', m: 'true friendship', c: 'People, Family & Relationships' },
    { w: '화목한 가족', p: 'hwamokhan gajok', m: 'harmonious family', c: 'People, Family & Relationships' },
    { w: '잊지 못할 추억', p: 'itji mothal chueok', m: 'unforgettable memory', c: 'Feelings, Emotions & Moods' },
    { w: '값진 성공', p: 'gapjin seonggong', m: 'valuable success', c: 'Feelings, Emotions & Moods' },
  ];

  const adjectives = [
    { w: '맛있다', p: 'masitda', m: 'delicious / tasty', c: 'Food, Cooking & Dining' },
    { w: '편리하다', p: 'pyeonrihada', m: 'convenient', c: 'Daily Life & Routine' },
    { w: '깨끗하다', p: 'kkaekkeuthada', m: 'clean', c: 'Home, Living & Interior' },
    { w: '아름답다', p: 'areumdapda', m: 'beautiful', c: 'Daily Life & Routine' },
    { w: '친절하다', p: 'chinjeolhada', m: 'kind / hospitable', c: 'People, Family & Relationships' },
    { w: '재미있다', p: 'jaemi-itda', m: 'fun / interesting', c: 'Hobbies, Arts & Pastimes' },
    { w: '쉽다', p: 'swipda', m: 'easy', c: 'School, Study & Education' },
    { w: '어렵다', p: 'eoryeopda', m: 'difficult', c: 'School, Study & Education' },
    { w: '빠르다', p: 'ppareuda', m: 'fast / quick', c: 'Travel, Transport & Directions' },
    { w: '즐겁다', p: 'jeulgeopda', m: 'pleasant / joyful', c: 'Feelings, Emotions & Moods' },
  ];

  const phrases = [
    { w: '안녕하세요', p: 'annyeonghaseyo', m: 'Hello / Good morning', c: 'Greetings & Introductions', exN: '안녕하세요, 오늘 날씨가 참 좋네요!', exP: 'annyeonghaseyo, oneul nalssiga cham jonneyo', exT: 'Hello, the weather is really nice today!' },
    { w: '감사합니다', p: 'gamsahamnida', m: 'Thank you very much', c: 'Politeness, Gratitude & Apologies', exN: '많은 도움을 주셔서 진심으로 감사합니다.', exP: 'maneun doumeul jusyeoseo jinsimeuro gamsahamnida', exT: 'Thank you sincerely for all the help.' },
    { w: '천만에요', p: 'cheonman-eyo', m: 'You are welcome', c: 'Politeness, Gratitude & Apologies', exN: '별말씀을요, 천만에요!', exP: 'byeolmalsseumeullyo, cheonman-eyo', exT: 'Do not mention it, you are welcome!' },
    { w: '안녕히 계세요', p: 'annyeonghi gyeseyo', m: 'Goodbye (to someone staying)', c: 'Greetings & Introductions', exN: '먼저 일어나 보겠습니다. 안녕히 계세요!', exP: 'meonjeo ireona bogesseumnida. annyeonghi gyeseyo', exT: 'I will be on my way first. Goodbye!' },
    { w: '수고하셨습니다', p: 'sugohasyeosseumnida', m: 'Thank you for your hard work', c: 'Work, Office & Business', exN: '오늘 하루도 모두 수고하셨습니다!', exP: 'oneul harudo modu sugohasyeosseumnida', exT: 'Thank you all for your hard work today as well!' },
  ];

  const questions = [
    { w: '화장실이 어디예요?', p: 'hwajangsiri eodiyeyo?', m: 'Where is the restroom?', exN: '저기 실례지만, 화장실이 어디예요?', exP: 'jeogi sillyejiman, hwajangsiri eodiyeyo?', exT: 'Excuse me over there, where is the restroom?' },
    { w: '이거 얼마예요?', p: 'igeo eolmayeyo?', m: 'How much is this?', exN: '사장님, 이 기념품 얼마예요?', exP: 'sajangnim, i ginyeompum eolmayeyo?', exT: 'Boss, how much is this souvenir?' },
    { w: '이름이 뭐예요?', p: 'ireumi mwoyeyo?', m: 'What is your name?', exN: '반갑습니다. 실례지만 성함이나 이름이 뭐예요?', exP: 'bangapseumnida. sillyejiman seonghamina ireumi mwoyeyo?', exT: 'Nice to meet you. Excuse me, what is your name?' },
    { w: '지금 몇 시예요?', p: 'jigeum myeot siyeyo?', m: 'What time is it now?', exN: '죄송한데, 지금 몇 시인지 알 수 있을까요?', exP: 'joesonghande, jigeum myeot si-inji al su isseulkkayo?', exT: 'Excuse me, could you let me know what time it is now?' },
  ];

  const responses = [
    { w: '네, 알겠습니다', p: 'ne, algessumnida', m: 'Yes, I understand', exN: '네, 말씀하신 대로 바로 처리하겠습니다.', exP: 'ne, malsseumhasin daero baro cheorihagessumnida', exT: 'Yes, I understand and will process it right as you said.' },
    { w: '괜찮아요', p: 'gwaenchanayo', m: 'It is okay / No problem', exN: '걱정하지 마세요, 정말 괜찮아요.', exP: 'geokjeonghaji maseyo, jeongmal gwaenchanayo', exT: 'Do not worry, it is truly fine.' },
    { w: '물론이죠', p: 'mullon-ijyo', m: 'Of course', exN: '물론이죠, 기꺼이 도와드릴게요.', exP: 'mullon-ijyo, gikkeo-i dowadeurilgeyo', exT: 'Of course, I will gladly assist you.' },
    { w: '맛있게 드세요', p: 'masitge deuseyo', m: 'Enjoy your meal', exN: '정성껏 준비했으니 맛있게 드세요!', exP: 'jeongseongkkeot junbihaesseuni masitge deuseyo', exT: 'Prepared with care, please enjoy your meal!' },
  ];

  return generateLanguageLibrary('ko', 'ko', {
    verbs,
    nouns,
    adjectives,
    phrases,
    questions,
    responses,
    buildExample: (v, n) => {
      return {
        n: `주말마다 여유롭게 ${n.w}을/를 ${v.w}.`,
        p: `Jumal-mada yeoyurobge ${n.p} ${v.p}.`,
        t: `Every weekend, I leisurely ${v.m} ${n.m}.`,
      };
    },
  });
}
