import { LearningItem } from '../../types/vocabulary';
import { generateLanguageLibrary } from '../generateAllLanguages';

export function generateFrenchDataset(): LearningItem[] {
  const verbs = [
    { w: 'manger', p: 'mɑ̃.ʒe', m: 'to eat', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'boire', p: 'bwaʁ', m: 'to drink', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'parler', p: 'paʁ.le', m: 'to speak / talk', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'écouter', p: 'e.ku.te', m: 'to listen to', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'regarder', p: 'ʁə.ɡaʁ.de', m: 'to watch / look at', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'lire', p: 'liʁ', m: 'to read', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'écrire', p: 'e.kʁiʁ', m: 'to write', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'acheter', p: 'aʃ.te', m: 'to buy', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'vendre', p: 'vɑ̃dʁ', m: 'to sell', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'voyager', p: 'vwa.ja.ʒe', m: 'to travel', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'marcher', p: 'maʁ.ʃe', m: 'to walk', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'courir', p: 'ku.ʁiʁ', m: 'to run', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'vivre', p: 'vivʁ', m: 'to live', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'travailler', p: 'tʁa.va.je', m: 'to work', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'se reposer', p: 'sə ʁə.po.ze', m: 'to rest', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'penser', p: 'pɑ̃.se', m: 'to think', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'décider', p: 'de.si.de', m: 'to decide', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'réserver', p: 'ʁe.zɛʁ.ve', m: 'to book / reserve', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'commander', p: 'kɔ.mɑ̃.de', m: 'to order', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'payer', p: 'pɛ.je', m: 'to pay', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'nettoyer', p: 'nɛ.twa.je', m: 'to clean', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'étudier', p: 'e.ty.dje', m: 'to study', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'apprendre', p: 'a.pʁɑ̃dʁ', m: 'to learn', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'aider', p: 'e.de', m: 'to help', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'chercher', p: 'ʃɛʁ.ʃe', m: 'to look for', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'trouver', p: 'tʁu.ve', m: 'to find', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'aimer', p: 'e.me', m: 'to love / like', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'vouloir', p: 'vu.lwaʁ', m: 'to want', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'pouvoir', p: 'pu.vwaʁ', m: 'to be able / can', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'connaître', p: 'kɔ.nɛtʁ', m: 'to know / be familiar with', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'appeler', p: 'ap.le', m: 'to call', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'envoyer', p: 'ɑ̃.vwa.je', m: 'to send', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'recevoir', p: 'ʁə.sə.vwaʁ', m: 'to receive', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'ouvrir', p: 'u.vʁiʁ', m: 'to open', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'fermer', p: 'fɛʁ.me', m: 'to close', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'prendre', p: 'pʁɑ̃dʁ', m: 'to take', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'attendre', p: 'a.tɑ̃dʁ', m: 'to wait for', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'commencer', p: 'kɔ.mɑ̃.se', m: 'to begin / start', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'finir', p: 'fi.niʁ', m: 'to finish / end', spec: { type: 'french', data: { verbGroup: 2 } } },
    { w: 'cuisiner', p: 'kɥi.zi.ne', m: 'to cook', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'pratiquer', p: 'pʁa.ti.ke', m: 'to practice', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'organiser', p: 'ɔʁ.ɡa.ni.ze', m: 'to organize', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'partager', p: 'paʁ.ta.ʒe', m: 'to share', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'visiter', p: 'vi.zi.te', m: 'to visit (a place)', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'comprendre', p: 'kɔ̃.pʁɑ̃dʁ', m: 'to understand', spec: { type: 'french', data: { verbGroup: 3 } } },
    { w: 'se rappeler', p: 'sə ʁa.ple', m: 'to remember', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'oublier', p: 'u.bli.je', m: 'to forget', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'préférer', p: 'pʁe.fe.ʁe', m: 'to prefer', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'changer', p: 'ʃɑ̃.ʒe', m: 'to change / exchange', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'utiliser', p: 'y.ti.li.ze', m: 'to use', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'apporter', p: 'a.pɔʁ.te', m: 'to bring', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'montrer', p: 'mɔ̃.tʁe', m: 'to show', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'expliquer', p: 'ɛks.pli.ke', m: 'to explain', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'présenter', p: 'pʁe.zɑ̃.te', m: 'to introduce / present', spec: { type: 'french', data: { verbGroup: 1 } } },
    { w: 'rencontrer', p: 'ʁɑ̃.kɔ̃.tʁe', m: 'to meet / encounter', spec: { type: 'french', data: { verbGroup: 1 } } },
  ];

  const nouns = [
    { w: 'le petit-déjeuner', p: 'lə pə.ti de.ʒœ.ne', m: 'the breakfast', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le déjeuner', p: 'lə de.ʒœ.ne', m: 'the lunch', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le dîner', p: 'lə di.ne', m: 'the dinner', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le croissant chaud', p: 'lə kʁwa.sɑ̃ ʃo', m: 'the hot croissant', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'la baguette fraîche', p: 'la ba.ɡɛt fʁɛʃ', m: 'the fresh baguette', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'le café au lait', p: 'lə ka.fe o lɛ', m: 'the coffee with milk', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'l’eau minérale', p: 'lo mi.ne.ʁal', m: 'the mineral water', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'feminine', article: "l'" } } },
    { w: 'le vin rouge', p: 'lə vɛ̃ ʁuʒ', m: 'the red wine', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le fromage affiné', p: 'lə fʁɔ.maʒ a.fi.ne', m: 'the aged cheese', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le train à grande vitesse (TGV)', p: 'lə tʁɛ̃', m: 'the high-speed bullet train (TGV)', c: 'Travel, Transport & Directions', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le billet de voyage', p: 'lə bi.jɛ də vwa.jaʒ', m: 'the travel ticket', c: 'Travel, Transport & Directions', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le passeport valide', p: 'lə pas.pɔʁ', m: 'the valid passport', c: 'Travel, Transport & Directions', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'la valise de voyage', p: 'la va.liz', m: 'the travel suitcase', c: 'Travel, Transport & Directions', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'l’aéroport de Paris', p: 'la.e.ʁɔ.pɔʁ', m: 'the Paris airport', c: 'Travel, Transport & Directions', spec: { type: 'french', data: { gender: 'masculine', article: "l'" } } },
    { w: 'la gare ferroviaire', p: 'la ɡaʁ', m: 'the railway station', c: 'Travel, Transport & Directions', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'l’hôtel confortable', p: 'lo.tɛl', m: 'the comfortable hotel', c: 'Travel, Transport & Directions', spec: { type: 'french', data: { gender: 'masculine', article: "l'" } } },
    { w: 'le plan de la ville', p: 'lə plɑ̃', m: 'the city map', c: 'Travel, Transport & Directions', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'la carte bancaire', p: 'la kaʁt bɑ̃.kɛʁ', m: 'the bank card', c: 'Shopping, Money & Finance', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'l’argent liquide', p: 'laʁ.ʒɑ̃ li.kid', m: 'the cash money', c: 'Shopping, Money & Finance', spec: { type: 'french', data: { gender: 'masculine', article: "l'" } } },
    { w: 'la facture détaillée', p: 'la fak.tyʁ', m: 'the itemized invoice', c: 'Shopping, Money & Finance', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'le téléphone intelligent', p: 'lə te.le.fɔn', m: 'the smartphone', c: 'Technology, Computers & Software', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'l’ordinateur portable', p: 'lɔʁ.di.na.tœʁ', m: 'the laptop computer', c: 'Technology, Computers & Software', spec: { type: 'french', data: { gender: 'masculine', article: "l'" } } },
    { w: 'les écouteurs sans fil', p: 'lez e.ku.tœʁ', m: 'the wireless earphones', c: 'Technology, Computers & Software', spec: { type: 'french', data: { gender: 'masculine', article: 'les' } } },
    { w: 'le message électronique', p: 'lə me.saʒ', m: 'the electronic message', c: 'Work, Office & Business', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le contrat commercial', p: 'lə kɔ̃.tʁa', m: 'the commercial contract', c: 'Work, Office & Business', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'la réunion d’équipe', p: 'la ʁe.y.njɔ̃', m: 'the team meeting', c: 'Work, Office & Business', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'le nouveau projet', p: 'lə pʁɔ.ʒɛ', m: 'the new project', c: 'Work, Office & Business', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le manuel de français', p: 'lə ma.nɥɛl', m: 'the French textbook', c: 'School, Study & Education', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'les devoirs du soir', p: 'le də.vwaʁ', m: 'the evening homework', c: 'School, Study & Education', spec: { type: 'french', data: { gender: 'masculine', article: 'les' } } },
    { w: 'l’examen important', p: 'lɛɡ.za.mɛ̃', m: 'the important exam', c: 'School, Study & Education', spec: { type: 'french', data: { gender: 'masculine', article: "l'" } } },
    { w: 'le médicament efficace', p: 'lə me.di.ka.mɑ̃', m: 'the effective medicine', c: 'Health, Body & Wellness', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le masque médical', p: 'lə mask', m: 'the medical mask', c: 'Health, Body & Wellness', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le manteau d’hiver', p: 'lə mɑ̃.to', m: 'the winter coat', c: 'Clothing & Fashion', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'les chaussures en cuir', p: 'le ʃo.syʁ', m: 'the leather shoes', c: 'Clothing & Fashion', spec: { type: 'french', data: { gender: 'feminine', article: 'les' } } },
    { w: 'la belle musique', p: 'la bɛl my.zik', m: 'the beautiful music', c: 'Entertainment, Music & Cinema', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'le cinéma français', p: 'lə si.ne.ma', m: 'the French cinema', c: 'Entertainment, Music & Cinema', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'la plage de sable', p: 'la plaʒ', m: 'the sandy beach', c: 'Nature, Geography & Cities', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la montagne majestueuse', p: 'la mɔ̃.taɲ', m: 'the majestic mountain', c: 'Nature, Geography & Cities', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'le beau soleil', p: 'lə bo sɔ.lɛj', m: 'the beautiful sunshine', c: 'Nature, Geography & Cities', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'la pluie d’automne', p: 'la plɥi', m: 'the autumn rain', c: 'Nature, Geography & Cities', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la culture française', p: 'la kyl.tyʁ', m: 'the French culture', c: 'Culture, Holidays & Traditions', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la fête nationale', p: 'la fɛt', m: 'the national holiday celebration', c: 'Culture, Holidays & Traditions', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'le cadeau surprise', p: 'lə ka.do', m: 'the surprise gift', c: 'Shopping, Money & Finance', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'la clé de la chambre', p: 'la kle', m: 'the room key', c: 'Home, Living & Interior', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'la chambre lumineuse', p: 'la ʃɑ̃bʁ', m: 'the bright bedroom', c: 'Home, Living & Interior', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'le dessert savoureux', p: 'lə de.sɛʁ', m: 'the flavorful dessert', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le verre d’eau', p: 'lə vɛʁ do', m: 'the glass of water', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'l’assiette de porcelaine', p: 'la.sjɛt', m: 'the porcelain plate', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'feminine', article: "l'" } } },
    { w: 'l’addition du restaurant', p: 'la.di.sjɔ̃', m: 'the restaurant bill', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'feminine', article: "l'" } } },
    { w: 'le serveur poli', p: 'lə sɛʁ.vœʁ', m: 'the polite waiter', c: 'Food, Cooking & Dining', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'la conversation amicale', p: 'la kɔ̃.vɛʁ.sa.sjɔ̃', m: 'the friendly conversation', c: 'Communication', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'l’amitié sincère', p: 'la.mi.tje', m: 'the sincere friendship', c: 'People, Family & Relationships', spec: { type: 'french', data: { gender: 'feminine', article: "l'" } } },
    { w: 'la belle famille', p: 'la bɛl fa.mij', m: 'the lovely family', c: 'People, Family & Relationships', spec: { type: 'french', data: { gender: 'feminine', article: 'la' } } },
    { w: 'le souvenir inoubliable', p: 'lə suv.niʁ', m: 'the unforgettable memory', c: 'Feelings, Emotions & Moods', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
    { w: 'le grand succès', p: 'lə ɡʁɑ̃ syk.sɛ', m: 'the great success', c: 'Feelings, Emotions & Moods', spec: { type: 'french', data: { gender: 'masculine', article: 'le' } } },
  ];

  const adjectives = [
    { w: 'délicieux', p: 'de.li.sjø', m: 'delicious', c: 'Food, Cooking & Dining' },
    { w: 'confortable', p: 'kɔ̃.fɔʁ.tabl', m: 'comfortable', c: 'Daily Life & Routine' },
    { w: 'propre', p: 'pʁɔpʁ', m: 'clean', c: 'Home, Living & Interior' },
    { w: 'magnifique', p: 'ma.ɲi.fik', m: 'magnificent / beautiful', c: 'Daily Life & Routine' },
    { w: 'gentil', p: 'ʒɑ̃.ti', m: 'kind / nice', c: 'People, Family & Relationships' },
    { w: 'intéressant', p: 'ɛ̃.te.ʁɛ.sɑ̃', m: 'interesting', c: 'School, Study & Education' },
    { w: 'facile', p: 'fa.sil', m: 'easy', c: 'School, Study & Education' },
    { w: 'difficile', p: 'di.fi.sil', m: 'difficult', c: 'School, Study & Education' },
    { w: 'rapide', p: 'ʁa.pid', m: 'fast / quick', c: 'Travel, Transport & Directions' },
    { w: 'agréable', p: 'a.ɡʁe.abl', m: 'pleasant / enjoyable', c: 'Daily Life & Routine' },
  ];

  const phrases = [
    { w: 'bonjour', p: 'bɔ̃.ʒuʁ', m: 'Good morning / Hello', c: 'Greetings & Introductions', exN: 'Bonjour, comment allez-vous aujourd’hui ?', exP: 'bɔ̃ʒuʁ, kɔmɑ̃ tale vu oʒuʁdɥi', exT: 'Hello, how are you doing today?' },
    { w: 'merci beaucoup', p: 'mɛʁ.si bo.ku', m: 'Thank you very much', c: 'Politeness, Gratitude & Apologies', exN: 'Merci beaucoup pour votre accueil chaleureux.', exP: 'mɛʁsi boku puʁ vɔtʁ akœj ʃaløʁø', exT: 'Thank you very much for your warm welcome.' },
    { w: 'de rien', p: 'də ʁjɛ̃', m: 'You are welcome', c: 'Politeness, Gratitude & Apologies', exN: 'Il n’y a pas de quoi, de rien.', exP: 'il nja pa də kwa, də ʁjɛ̃', exT: 'It is nothing at all, you are welcome.' },
    { w: 'au revoir', p: 'o ʁə.vwaʁ', m: 'Goodbye', c: 'Greetings & Introductions', exN: 'Bonne journée et au revoir !', exP: 'bɔn ʒuʁne e o ʁəvwaʁ', exT: 'Have a good day and goodbye!' },
    { w: 'avec plaisir', p: 'a.vɛk ple.ziʁ', m: 'With pleasure', c: 'Everyday Responses & Reactions', exN: 'C’est avec grand plaisir que je vous aide.', exP: 'sɛ a.vɛk ɡʁɑ̃ pleziʁ kə ʒə vuz ɛd', exT: 'It is with great pleasure that I help you.' },
  ];

  const questions = [
    { w: 'Où sont les toilettes ?', p: 'u sɔ̃ le twa.lɛt', m: 'Where is the restroom?', exN: 'Pardon monsieur, où sont les toilettes s’il vous plaît ?', exP: 'paʁdɔ̃ məsjø, u sɔ̃ le twalɛt sil vu plɛ', exT: 'Excuse me sir, where are the restrooms please?' },
    { w: 'Combien ça coûte ?', p: 'kɔ̃.bjɛ̃ sa kut', m: 'How much does this cost?', exN: 'S’il vous plaît, combien ça coûte cette pâtisserie ?', exP: 'sil vu plɛ, kɔ̃bjɛ̃ sa kut sɛt patisʁi', exT: 'Please, how much does this pastry cost?' },
    { w: 'Comment vous vous appelez ?', p: 'kɔ.mɑ̃ vu vu za.ple', m: 'What is your name?', exN: 'Ravi de vous rencontrer, comment vous vous appelez ?', exP: 'ʁavi də vu ʁɑ̃kɔ̃tʁe, kɔmɑ̃ vu vu zaple', exT: 'Delighted to meet you, what is your name?' },
    { w: 'Quelle heure est-il ?', p: 'kɛl œʁ ɛ.til', m: 'What time is it?', exN: 'Excusez-moi, pourriez-vous me dire quelle heure est-il ?', exP: 'ɛkskyze mwa, puʁje vu mə diʁ kɛl œʁ ɛtil', exT: 'Excuse me, could you tell me what time it is?' },
  ];

  const responses = [
    { w: 'bien sûr', p: 'bjɛ̃ syʁ', m: 'Of course', exN: 'Bien sûr, vous pouvez vous asseoir ici.', exP: 'bjɛ̃ syʁ, vu puve vuz aswaʁ isi', exT: 'Of course, you can sit here.' },
    { w: 'ce n’est pas grave', p: 'sə nɛ pa ɡʁav', m: 'It does not matter', exN: 'Ne vous inquiétez pas, ce n’est pas grave du tout.', exP: 'nə vu zɛ̃kjete pa, sə nɛ pa ɡʁav dy tu', exT: 'Do not worry, it is not serious at all.' },
    { w: 'je suis d’accord', p: 'ʒə sɥi da.kɔʁ', m: 'I agree', exN: 'Absolument, je suis entièrement d’accord avec vous.', exP: 'apsɔlymɑ̃, ʒə sɥi ɑ̃tjɛʁmɑ̃ dakɔʁ avɛk vu', exT: 'Absolutely, I entirely agree with you.' },
    { w: 'bon appétit', p: 'bɔ̃ a.pe.ti', m: 'Enjoy your meal', exN: 'Bon appétit à tous autour de la table !', exP: 'bɔ̃n apeti a tus otuʁ də la tabl', exT: 'Enjoy your meal everyone around the table!' },
  ];

  return generateLanguageLibrary('fr', 'fr', {
    verbs,
    nouns,
    adjectives,
    phrases,
    questions,
    responses,
    buildExample: (v, n) => {
      return {
        n: `J’aime beaucoup ${v.w} ${n.w} chaque semaine.`,
        p: `ʒɛm boku ${v.p} ${n.p}`,
        t: `I really enjoy to ${v.m} ${n.m} every week.`,
      };
    },
  });
}
